[project]
name = "machine-learning-tech-challenge04"
version = "0.1.0"
description = ""
authors = [
    {name = "davicoene",email = "davicoenerosa@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "pandas (>=3.0.6,<4.0.0)",
    "scikit-learn (>=1.9.1,<2.0.0)",
    "xgboost (>=3.4.1,<4.0.0)",
    "pandera (>=0.34.1,<0.35.0)",
    "evidently (>=0.7.23,<0.8.0)",
    "mlflow (>=3.17.0,<4.0.0)",
    "fastapi (>=0.142.4,<0.143.0)",
    "uvicorn (>=0.54.0,<0.55.0)",
    "pyyaml (>=6.0.3,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "ruff (>=0.16.10,<0.17.0)"
]
